// <auto-generated />
#pragma warning disable CS0105
/*Auto Create, Don't Edit !!!*/

using UnityEngine;
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.IO;
using System;
using DummyEgg.MasterDataWorker.Tables;

namespace DummyEgg.MasterDataWorker
{
    public class MasterMemoryResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new MasterMemoryResolver();

        MasterMemoryResolver()
        {

        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.formatter;
        }

        static class FormatterCache<T>
        {
            public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> formatter;

            static FormatterCache()
            {
                var f = MasterMemoryResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class MasterMemoryResolverGetFormatterHelper
    {
        static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static MasterMemoryResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(5)
            {
                {typeof(MstExp_MMItem[]), 0 },
                {typeof(MstJobBaseData_MMItem[]), 1 },
                {typeof(MstJobDesc_MMItem[]), 2 },
                {typeof(MstJobProgress_MMItem[]), 3 },
                {typeof(mst_test_data_MMItem[]), 4 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key)) return null;

            switch (key)
            {
                case 0: return new MessagePack.Formatters.ArrayFormatter<MstExp_MMItem>();
                case 1: return new MessagePack.Formatters.ArrayFormatter<MstJobBaseData_MMItem>();
                case 2: return new MessagePack.Formatters.ArrayFormatter<MstJobDesc_MMItem>();
                case 3: return new MessagePack.Formatters.ArrayFormatter<MstJobProgress_MMItem>();
                case 4: return new MessagePack.Formatters.ArrayFormatter<mst_test_data_MMItem>();
                default: return null;
            }
        }
    }
}