// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace DummyEgg.MasterDataWorker.Resolvers
{
    public class MmGeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new MmGeneratedResolver();

        private MmGeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = MmGeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class MmGeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static MmGeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5)
            {
                { typeof(global::mst_test_data_MMItem), 0 },
                { typeof(global::MstExp_MMItem), 1 },
                { typeof(global::MstJobBaseData_MMItem), 2 },
                { typeof(global::MstJobDesc_MMItem), 3 },
                { typeof(global::MstJobProgress_MMItem), 4 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new DummyEgg.MasterDataWorker.Formatters.mst_test_data_MMItemFormatter();
                case 1: return new DummyEgg.MasterDataWorker.Formatters.MstExp_MMItemFormatter();
                case 2: return new DummyEgg.MasterDataWorker.Formatters.MstJobBaseData_MMItemFormatter();
                case 3: return new DummyEgg.MasterDataWorker.Formatters.MstJobDesc_MMItemFormatter();
                case 4: return new DummyEgg.MasterDataWorker.Formatters.MstJobProgress_MMItemFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name




// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace DummyEgg.MasterDataWorker.Formatters
{
    public sealed class mst_test_data_MMItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::mst_test_data_MMItem>
    {
        // test_id
        private static global::System.ReadOnlySpan<byte> GetSpan_test_id() => new byte[1 + 7] { 167, 116, 101, 115, 116, 95, 105, 100 };
        // test_str
        private static global::System.ReadOnlySpan<byte> GetSpan_test_str() => new byte[1 + 8] { 168, 116, 101, 115, 116, 95, 115, 116, 114 };
        // test_group
        private static global::System.ReadOnlySpan<byte> GetSpan_test_group() => new byte[1 + 10] { 170, 116, 101, 115, 116, 95, 103, 114, 111, 117, 112 };
        // test_float
        private static global::System.ReadOnlySpan<byte> GetSpan_test_float() => new byte[1 + 10] { 170, 116, 101, 115, 116, 95, 102, 108, 111, 97, 116 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::mst_test_data_MMItem value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(4);
            writer.WriteRaw(GetSpan_test_id());
            writer.Write(value.test_id);
            writer.WriteRaw(GetSpan_test_str());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.test_str, options);
            writer.WriteRaw(GetSpan_test_group());
            writer.Write(value.test_group);
            writer.WriteRaw(GetSpan_test_float());
            writer.Write(value.test_float);
        }

        public global::mst_test_data_MMItem Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __test_id__ = default(uint);
            var __test_str__ = default(string);
            var __test_group__ = default(uint);
            var __test_float__ = default(float);

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 7:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 28263356367594868UL) { goto FAIL; }

                        __test_id__ = reader.ReadUInt32();
                        continue;
                    case 8:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 8247343671435027828UL) { goto FAIL; }

                        __test_str__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 10:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 8030594745228289396UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 28789UL) { goto FAIL; }

                                __test_group__ = reader.ReadUInt32();
                                continue;

                            case 8028904795856397684UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 29793UL) { goto FAIL; }

                                __test_float__ = reader.ReadSingle();
                                continue;

                        }

                }
            }

            var ____result = new global::mst_test_data_MMItem(__test_id__, __test_str__, __test_group__, __test_float__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MstExp_MMItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MstExp_MMItem>
    {
        // lv
        private static global::System.ReadOnlySpan<byte> GetSpan_lv() => new byte[1 + 2] { 162, 108, 118 };
        // needExp
        private static global::System.ReadOnlySpan<byte> GetSpan_needExp() => new byte[1 + 7] { 167, 110, 101, 101, 100, 69, 120, 112 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::MstExp_MMItem value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteMapHeader(2);
            writer.WriteRaw(GetSpan_lv());
            writer.Write(value.lv);
            writer.WriteRaw(GetSpan_needExp());
            writer.Write(value.needExp);
        }

        public global::MstExp_MMItem Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadMapHeader();
            var ____result = new global::MstExp_MMItem();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 2:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 30316UL) { goto FAIL; }

                        ____result.lv = reader.ReadInt32();
                        continue;
                    case 7:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 31657436824036718UL) { goto FAIL; }

                        ____result.needExp = reader.ReadInt32();
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MstJobBaseData_MMItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MstJobBaseData_MMItem>
    {
        // job_id
        private static global::System.ReadOnlySpan<byte> GetSpan_job_id() => new byte[1 + 6] { 166, 106, 111, 98, 95, 105, 100 };
        // hp
        private static global::System.ReadOnlySpan<byte> GetSpan_hp() => new byte[1 + 2] { 162, 104, 112 };
        // mp
        private static global::System.ReadOnlySpan<byte> GetSpan_mp() => new byte[1 + 2] { 162, 109, 112 };
        // phy_atk
        private static global::System.ReadOnlySpan<byte> GetSpan_phy_atk() => new byte[1 + 7] { 167, 112, 104, 121, 95, 97, 116, 107 };
        // phy_def
        private static global::System.ReadOnlySpan<byte> GetSpan_phy_def() => new byte[1 + 7] { 167, 112, 104, 121, 95, 100, 101, 102 };
        // mag_atk
        private static global::System.ReadOnlySpan<byte> GetSpan_mag_atk() => new byte[1 + 7] { 167, 109, 97, 103, 95, 97, 116, 107 };
        // mag_def
        private static global::System.ReadOnlySpan<byte> GetSpan_mag_def() => new byte[1 + 7] { 167, 109, 97, 103, 95, 100, 101, 102 };
        // dex
        private static global::System.ReadOnlySpan<byte> GetSpan_dex() => new byte[1 + 3] { 163, 100, 101, 120 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::MstJobBaseData_MMItem value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteMapHeader(8);
            writer.WriteRaw(GetSpan_job_id());
            writer.Write(value.job_id);
            writer.WriteRaw(GetSpan_hp());
            writer.Write(value.hp);
            writer.WriteRaw(GetSpan_mp());
            writer.Write(value.mp);
            writer.WriteRaw(GetSpan_phy_atk());
            writer.Write(value.phy_atk);
            writer.WriteRaw(GetSpan_phy_def());
            writer.Write(value.phy_def);
            writer.WriteRaw(GetSpan_mag_atk());
            writer.Write(value.mag_atk);
            writer.WriteRaw(GetSpan_mag_def());
            writer.Write(value.mag_def);
            writer.WriteRaw(GetSpan_dex());
            writer.Write(value.dex);
        }

        public global::MstJobBaseData_MMItem Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadMapHeader();
            var __job_id__ = default(int);
            var __hp__ = default(int);
            var __mp__ = default(int);
            var __phy_atk__ = default(int);
            var __phy_def__ = default(int);
            var __mag_atk__ = default(int);
            var __mag_def__ = default(int);
            var __dex__ = default(int);

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 6:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 110403734630250UL) { goto FAIL; }

                        __job_id__ = reader.ReadInt32();
                        continue;
                    case 2:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 28776UL:
                                __hp__ = reader.ReadInt32();
                                continue;
                            case 28781UL:
                                __mp__ = reader.ReadInt32();
                                continue;
                        }
                    case 7:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 30245784070482032UL:
                                __phy_atk__ = reader.ReadInt32();
                                continue;
                            case 28821929397414000UL:
                                __phy_def__ = reader.ReadInt32();
                                continue;
                            case 30245784069300589UL:
                                __mag_atk__ = reader.ReadInt32();
                                continue;
                            case 28821929396232557UL:
                                __mag_def__ = reader.ReadInt32();
                                continue;
                        }
                    case 3:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 7890276UL) { goto FAIL; }

                        __dex__ = reader.ReadInt32();
                        continue;

                }
            }

            var ____result = new global::MstJobBaseData_MMItem(__job_id__, __hp__, __mp__, __phy_atk__, __phy_def__, __mag_atk__, __mag_def__, __dex__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MstJobDesc_MMItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MstJobDesc_MMItem>
    {
        // job_id
        private static global::System.ReadOnlySpan<byte> GetSpan_job_id() => new byte[1 + 6] { 166, 106, 111, 98, 95, 105, 100 };
        // name
        private static global::System.ReadOnlySpan<byte> GetSpan_name() => new byte[1 + 4] { 164, 110, 97, 109, 101 };
        // desc
        private static global::System.ReadOnlySpan<byte> GetSpan_desc() => new byte[1 + 4] { 164, 100, 101, 115, 99 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::MstJobDesc_MMItem value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(3);
            writer.WriteRaw(GetSpan_job_id());
            writer.Write(value.job_id);
            writer.WriteRaw(GetSpan_name());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.name, options);
            writer.WriteRaw(GetSpan_desc());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.desc, options);
        }

        public global::MstJobDesc_MMItem Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __job_id__ = default(int);
            var __name__ = default(string);
            var __desc__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 6:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 110403734630250UL) { goto FAIL; }

                        __job_id__ = reader.ReadInt32();
                        continue;
                    case 4:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 1701667182UL:
                                __name__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                                continue;
                            case 1668506980UL:
                                __desc__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                                continue;
                        }

                }
            }

            var ____result = new global::MstJobDesc_MMItem(__job_id__, __name__, __desc__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MstJobProgress_MMItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MstJobProgress_MMItem>
    {
        // job_id
        private static global::System.ReadOnlySpan<byte> GetSpan_job_id() => new byte[1 + 6] { 166, 106, 111, 98, 95, 105, 100 };
        // hp
        private static global::System.ReadOnlySpan<byte> GetSpan_hp() => new byte[1 + 2] { 162, 104, 112 };
        // mp
        private static global::System.ReadOnlySpan<byte> GetSpan_mp() => new byte[1 + 2] { 162, 109, 112 };
        // phy_atk
        private static global::System.ReadOnlySpan<byte> GetSpan_phy_atk() => new byte[1 + 7] { 167, 112, 104, 121, 95, 97, 116, 107 };
        // phy_def
        private static global::System.ReadOnlySpan<byte> GetSpan_phy_def() => new byte[1 + 7] { 167, 112, 104, 121, 95, 100, 101, 102 };
        // mag_atk
        private static global::System.ReadOnlySpan<byte> GetSpan_mag_atk() => new byte[1 + 7] { 167, 109, 97, 103, 95, 97, 116, 107 };
        // mag_def
        private static global::System.ReadOnlySpan<byte> GetSpan_mag_def() => new byte[1 + 7] { 167, 109, 97, 103, 95, 100, 101, 102 };
        // dex
        private static global::System.ReadOnlySpan<byte> GetSpan_dex() => new byte[1 + 3] { 163, 100, 101, 120 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::MstJobProgress_MMItem value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteMapHeader(8);
            writer.WriteRaw(GetSpan_job_id());
            writer.Write(value.job_id);
            writer.WriteRaw(GetSpan_hp());
            writer.Write(value.hp);
            writer.WriteRaw(GetSpan_mp());
            writer.Write(value.mp);
            writer.WriteRaw(GetSpan_phy_atk());
            writer.Write(value.phy_atk);
            writer.WriteRaw(GetSpan_phy_def());
            writer.Write(value.phy_def);
            writer.WriteRaw(GetSpan_mag_atk());
            writer.Write(value.mag_atk);
            writer.WriteRaw(GetSpan_mag_def());
            writer.Write(value.mag_def);
            writer.WriteRaw(GetSpan_dex());
            writer.Write(value.dex);
        }

        public global::MstJobProgress_MMItem Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadMapHeader();
            var __job_id__ = default(int);
            var __hp__ = default(int);
            var __mp__ = default(int);
            var __phy_atk__ = default(int);
            var __phy_def__ = default(int);
            var __mag_atk__ = default(int);
            var __mag_def__ = default(int);
            var __dex__ = default(int);

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 6:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 110403734630250UL) { goto FAIL; }

                        __job_id__ = reader.ReadInt32();
                        continue;
                    case 2:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 28776UL:
                                __hp__ = reader.ReadInt32();
                                continue;
                            case 28781UL:
                                __mp__ = reader.ReadInt32();
                                continue;
                        }
                    case 7:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 30245784070482032UL:
                                __phy_atk__ = reader.ReadInt32();
                                continue;
                            case 28821929397414000UL:
                                __phy_def__ = reader.ReadInt32();
                                continue;
                            case 30245784069300589UL:
                                __mag_atk__ = reader.ReadInt32();
                                continue;
                            case 28821929396232557UL:
                                __mag_def__ = reader.ReadInt32();
                                continue;
                        }
                    case 3:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 7890276UL) { goto FAIL; }

                        __dex__ = reader.ReadInt32();
                        continue;

                }
            }

            var ____result = new global::MstJobProgress_MMItem(__job_id__, __hp__, __mp__, __phy_atk__, __phy_def__, __mag_atk__, __mag_def__, __dex__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

